dist: xenial
language: node_js
node_js:
 - "16.14.0"
matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
      - sudo add-apt-repository ppa:deadsnakes/ppa
      - sudo apt-get update
      - sudo apt-get install Python3.7
install:
  - bash ./bin/travis-install.sh
script:
  - bash ./bin/test.sh
after_script:
 - bash <(curl -s https://codecov.io/bash)