dist: xenial
language: node_js
node_js:
 - "16.14.0"
matrix:
  include:
      os: linux
      dist: xenial
      before_install:
      - apt-get update && apt-get install build-essential
install:
  - bash ./bin/travis-install.sh
script:
  - bash ./bin/test.sh
after_script:
 - bash <(curl -s https://codecov.io/bash)